[STINS 011] Implement buttons
UoaWDCC/Stick-Insect pull request #13
Opened 2021-08-20 06:30 UTC by jzha411

issue:
Implements buttons in frontend

Solution:
Creating the connections between pages using interactive buttons for the Stick Insect project.

Risk:
No risk.

Reviewed by:
Jason, Jason, Lucas

2021-08-20 11:21 UTC, lucas2005gao commented
Hey Jason!! I havn't thoroughly read through the functional changes of this PR yet but can you please go to the Github Actions and have a look at the errors the ESLint and Prettier is giving you:
![image](https://user-images.githubusercontent.com/48196609/130225932-46d8af74-9e76-479e-90a6-60b28083e8a5.png)
Click on details and it will tell you

2021-08-20 11:22 UTC, lucas2005gao commented
You will need to first npm install again to install the dependencies I added, then run `npm run lint:fix` in the frontend folder!
run `npm run lint` again to see if the everything is passing

2021-08-20 11:22 UTC, lucas2005gao requested changes
You will need to first npm install again to install the dependencies I added, then run npm run lint:fix in the frontend folder!
run npm run lint again to see if the everything is passing

2021-08-20 12:30 UTC, jzha411 reviewed
Reviewed all changes

2021-08-20 13:39 UTC, lucas2005gao approved these changes
Nice!! Great work!

2021-08-21 02:44 UTC, aidandayvyd approved these changes
LGTM :)

2021-08-21 12:05 UTC, jekb2019 approved these changes

2021-08-21 13:49 UTC, dlee658 approved these changes

2021-08-21 13:49 UTC, dlee658 commented on frontend/src/components/ConsentPage.js
> +        {" "}
Just saying, {" "}, this is added by prettier, that automatically format code.
It does not really matter, but you can remove this line of code.

2021-08-22 00:36 UTC, merged